# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32335816848776226e6bf3c5bd13eed772e2c9fa67aeb8cd902700e019b4f8acdd853f9d234cd56ebbcc8f6d372f33e853081a539b3e6b49e8a10d63235e312d

test:
  secret_key_base: 2ff6f3cb37f7c393084b0283fdafbfe665e3da8395ffd1d70844e2d5f3f97d6f67bc82c6e6e9e620b106771f238633a15efdfabf1dc45383af80889e4c7c77f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
